/**
 * List of valid surgery types used in dropdown selectors across the application.
 * Update this list if new surgery types are introduced.
 */
export const SURGERY_TYPES = [
  'Adenoidectomy',
  'Adenoidectomy with Ear Ventilation',
  'Adenotonsillectomy',
  'Tonsillectomy',
  'Maxillary Antrostomy',
  'ENT Biopsy',
  'Canaloplasty',
  'Cholesteatoma Surgery',
  'Endoscopic Sinus Surgery (ESS)',
  'General Consultation',
  'Cordectomy',
  'Dacryocystorhinostomy',
  'Sphenoidotomy',
  'Stapedotomy',
  'Ethmoidectomy',
  'Complete Neck Dissection',
  'Pharyngoplasty',
  'Lingual Frenotomy',
  'Cochlear Implant',
  'Suspension Laryngoscopy',
  'Mastoidectomy',
  'Laryngeal Microsurgery',
  'Myringoplasty',
  'Myringotomy',
  'Myringotomy with Ventilation Tube Placement',
  'Ossiculoplasty',
  'Otoplasty',
  'Otosclerosis Surgery',
  'Parotidectomy',
  'Nasal Polypectomy',
  'Vocal Cord Polyp Removal',
  'Rhinoplasty',
  'Rhinoseptoplasty',
  'Septoplasty',
  'Frontal Sinusotomy',
  'Submandibular Gland Removal',
  'Tympanomastoidectomy',
  'Tympanoplasty',
  'Thyroidectomy',
  'Tracheostomy',
  'Ventilation Tubes',
  'Turbinectomy',
  'Turbinoplasty (Turbinate Reduction)',
  'Uvulopalatopharyngoplasty',
  'Other'
];

/**
 * List of valid health insurance types used in dropdown selectors across the application.
 * Update this list if new insurance providers are added.
 */
export const INSURANCE_TYPES = [
  'HealthGuard',
  'PrimeHealth',
  'Aetna',
  'Allianz',
  'Cigna',
  'Fidelity Health',
  'Future Healthcare',
  'Generali',
  'GNB',
  'Public Security Fund',
  'MediCare Plus',
  'WellPoint',
  'Mgen',
  'Mudum',
  'National Health Service',
  'Private',
  'Planicare',
  'RNA Medical',
  'Public Sector Assistance',
  'CareFirst',
  'CareFirst Executive',
  'National Health Coordination',
  'Tranquility Health',
  'Una Insurance',
  'Victoria',
  'Wells',
  'Other'
];