// <auto-generated />
using System;
using CustomerManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260204175300_InitialCreateWithCascade")]
    partial class InitialCreateWithCascade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("CustomerManagement.Domain.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ClientDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InsuranceType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SCMLCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SurgeryType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId");

                    b.HasIndex("LocationId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CustomerManagement.Domain.Models.DailyEntry", b =>
                {
                    b.Property<int>("DailyEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("TEXT");

                    b.HasKey("DailyEntryId");

                    b.HasIndex("LocationId");

                    b.ToTable("DailyEntries");
                });

            modelBuilder.Entity("CustomerManagement.Domain.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("CustomerManagement.Domain.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DailyEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PaymentId");

                    b.HasIndex("ClientId");

                    b.HasIndex("DailyEntryId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CustomerManagement.Domain.Models.ReportHistory", b =>
                {
                    b.Property<int>("ReportHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilterCriteriaJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ReportHistoryId");

                    b.ToTable("ReportHistories");
                });

            modelBuilder.Entity("CustomerManagement.Domain.Models.Client", b =>
                {
                    b.HasOne("CustomerManagement.Domain.Models.Location", "Location")
                        .WithMany("Clients")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CustomerManagement.Domain.Models.DailyEntry", b =>
                {
                    b.HasOne("CustomerManagement.Domain.Models.Location", "Location")
                        .WithMany("DailyEntries")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CustomerManagement.Domain.Models.Payment", b =>
                {
                    b.HasOne("CustomerManagement.Domain.Models.Client", "Client")
                        .WithMany("Payments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CustomerManagement.Domain.Models.DailyEntry", "DailyEntry")
                        .WithMany("Payments")
                        .HasForeignKey("DailyEntryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Client");

                    b.Navigation("DailyEntry");
                });

            modelBuilder.Entity("CustomerManagement.Domain.Models.Client", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CustomerManagement.Domain.Models.DailyEntry", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CustomerManagement.Domain.Models.Location", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("DailyEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
